[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.96"
jni = "0.21"
thiserror = "2.0.11"

[profile.release]
lto = true
codegen-units = 1
